### ISSUE TITLE
Make Github Login.

### ISSUE THREAD

**Issue by yashsaxena** [Openfuel/openfuel#1]
Also we need the phone number of the user to get in touch. So we need to add a field for adding mobile number. LATER we can use OTP to authenticate the phone number.

**Comment by DivySrivastava** [comment]
Completed GitHub Auth #3072c7e

**Comment by dan-online** [comment]
@yashsaxena shouldn’t we use email for that and phone numbers for two factor?

**Comment by DivySrivastava** [comment]
I agree with @dan-online 
We can use either nodemailer or we can have a new service for sending openfuel mails.

**Comment by DivySrivastava** [comment]
@yashsaxena Twilio for SMS?

**Comment by yashsaxena** [comment]
@dan-online @DivySrivastava Yes we should add phone number verification for sure and then cud be twilio or msg91 for sms...
