### ISSUE TITLE
Create a more prominent search option

### ISSUE THREAD

**Issue by yashsaxena** [Openfuel/openfuel#14]
#13 connected partially to this issue - We need to have a way to search user profiles by expertise areas ( languages and repositories). So while we could have a search option in the profiles feed under 'Network' but we can also have ths same in the current search option. Currently we can search by language but it would be better if we could do the same by just typing in the words and then getting suggested autotags (for bothe repositories and language) - like we search in stackoverflow.

If someone is looking for prometheus developers, then the search will be the primary option - so we should make search option more prominent. We can make it bold - a bold color.

**Comment by dan-online** [comment]
Added in commits: [[d7b2eb3](https://github.com/Openfuel/openfuel/commit/d7b2eb3f3191ee9a0f13ff4cc7c8d7ae453f0e99), [9bcca5f](https://github.com/Openfuel/openfuel/commit/9bcca5f218d32842194aa8752ab6a02cefa4a018)]
