### ISSUE TITLE
Color scheme for learning/expertise level for repo/language tags

### ISSUE THREAD

**Issue by yashsaxena** [Openfuel/openfuel#16]
![profile-default-repo](https://user-images.githubusercontent.com/1704774/68083558-fd79cc00-fe4f-11e9-8902-5a793ccfb5ee.png)

We could have a blue tag for the repos a developer has worked on.  But if someone is looking for a developer in a certain language or repository - then we should help that by giving some color coding in each area. This *MAY*need some enhancement also in the original github repo we used to pull the git info. If that original repo is pulling in repo contribution numbers, we could make a color scheme just bu the number of contributions. If that repo is not giving contribution numbers then we could actuall add that feature to the original repo and use it here ( will enhance original repo as well)

We can have Say green for high expertise...orange for medium...yellow for low. When we get more stats from github we can make these colors more accurate.

Also #15 where I add expertise areas by myself - we cud give it a grey or white color - to show this is a user added area but not verified by github data.

**Comment by yashsaxena** [comment]
@dan-online we can discuss this issue - if you think there is something that needs discussion.

**Comment by dan-online** [comment]
Added in commit: [[1a86dc8](https://github.com/Openfuel/openfuel/commit/1a86dc8ab1e96d8563ebf18a902fb5a201c3e061)]
