### ISSUE TITLE
Profile expertise areas shown as default

### ISSUE THREAD

**Issue by yashsaxena** [Openfuel/openfuel#17]
![profile-default-repo](https://user-images.githubusercontent.com/1704774/68083531-a1af4300-fe4f-11e9-8c75-1ea2c95c512c.png)

Lets make the Repo information as the default selected option on profile page.Since looking at expertise of a developer and searching by them is more primary on platform. Posts under Overview can be selected to show.

**Comment by dan-online** [comment]
Added in commit: [[4fef948](https://github.com/Openfuel/openfuel/commit/4fef948381cf77c4aeab574a57c77bcfd0e35077)]
