### ISSUE TITLE
Billing Issues?

### ISSUE THREAD

**Issue by dan-online** [Openfuel/openfuel#18]
```
We are having a problem billing the Openfuel organization. 
Please update your payment method or call your payment provider for details on why the transaction failed. 
If you don’t need access to your private repositories, you can downgrade to GitHub Team For Open Source.
You can always contact support with any questions.
```

**Comment by yashsaxena** [comment]
@dan-online I'mon it Dan - I'm trying to pay through paypal but its not working. So I have raised a ticket. My credit card is being renewed - with which I signed up - it should arrive by 8th october. So if paypal works I should be able to get it done tomorrow, if paypal issue exists - I'll be able to fix billing by 8th when I get my new card.

**Comment by dan-online** [comment]
Ok great!
