### ISSUE TITLE
Add 'tags' in profile

### ISSUE THREAD

**Issue by yashsaxena** [Openfuel/openfuel#2]
Thse tags will be area of expertise like languages known, repositories worked upon ( eg. Spruce, agendash etc.) and other things as we come across later.

We will make these tags searchable through main page.

**Comment by DivySrivastava** [comment]
Language wise tags have been added, and a user can search using this filter :smile:

**Comment by yashsaxena** [comment]
Repo wise tags are also there - search through them is a different issue. So Im closing this.
